owner: React-it
repo: IDCerberus-Status-Page

sites:
  - name: Landing Page
    url: https://idcerberus.com

  - name: Backoffice Producao
    url: https://backoffice.idcerberus.com/

  - name: Backoffice Homologacao
    url: https://backoffice-hml.idcerberus.com/

status-website:
  baseUrl: /IDCerberus-Status-Page
  theme: dark
  themeUrl: https://React-it.github.io/IDCerberus-Status-Page/idcerberus-theme.css
  name: IDCerberus Status
  introTitle: ""
  introMessage: ""
  logoUrl: https://React-it.github.io/IDCerberus-Status-Page/logo.webp
  favicon: https://idcerberus.com/favicon.ico
  metaTags:
    - name: "theme-color"
      content: "#081c24"
    - name: "robots"
      content: "index, follow"
  customHeadHtml: "<meta name='apple-mobile-web-app-title' content='IDCerberus Status'>"
  navbar:
    - title: Status
      href: /IDCerberus-Status-Page/
    - title: IDCerberus
      href: https://idcerberus.com
    - title: Producao
      href: https://backoffice.idcerberus.com/
    - title: Homologacao
      href: https://backoffice-hml.idcerberus.com/

assignees:
  - jorginholys

user-agent: React-it

i18n:
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os servicos operacionais
  incidentReport: Relatorio de incidente
  overallUptime: Disponibilidade geral
  responseTime: Tempo de resposta
  uptime: Disponibilidade
  footer: Pagina publica de status do IDCerberus
